version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./phonebook-nginx.conf:/etc/nginx/conf.d/phonebook.conf
  phonebook:
    build: .
    environment:
      - DATABASE=/phone-book/database/dbsecret.py
  mysql:
    image: mysql:5.7
    #    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=app
      - MYSQL_PASSWORD=qwer
