apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  database: /phone-book/config/dbsecret.py
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-app
  template:
    metadata:
      labels:
        app: phonebook-app
    spec:
      imagePullSecrets:
      - name: registrypullsecret            
      containers:
      - name: phonebook
        image: devopsnexus/phonebook
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /phone-book/config/
          name: app-config
      volumes:
      - name: app-config
        secret:
          secretName: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-app-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: phonebook-app
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-migration
spec:
  template:
    metadata:
      name: app-migration
    spec:
      restartPolicy: Never            
      imagePullSecrets:
      - name: registrypullsecret      
      containers:
      - name: app-migration
        image: devopsnexus/phonebook
        command: ["/bin/bash"]
        args: ["/phone-book/init.sh"]
        env:
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database  
